### ISSUE TITLE
Bug in PCSKeys.js

### ISSUE THREAD

**Issue by otfried** [matafokka/geotiff-geokeys-to-proj4#1]
There seems to be a bug in lines 108 & 109 of `EPSG/data/PCSKeys.js`:
```
k.o3.ProjOriginLatGeoKey = k.ProjNatOriginLatGeoKey;
k.o3.ProjScaleAtOriginGeoKey = k.ProjScaleAtNatOriginGeoKey;
```
It think this should be:
```
k.o3.ProjOriginLatGeoKey = k.o2.ProjNatOriginLatGeoKey;
k.o3.ProjScaleAtOriginGeoKey = k.o2.ProjScaleAtNatOriginGeoKey;
```

**Comment by otfried** [comment]
Many thanks for the quick fix and the new release!

Unfortunately, my geotiff file still doesn't work.  I will make a new issue.

**Comment by matafokka** [comment]
Sorry to hear that. Can you send me geokeys (output of `geotiff.getGeoKeys()` and a Proj4 string that your favorite GIS generates? I'll look what I can do tomorrow.
